---
title: "dendro_plot"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Loading required packages:
```{r}
library(distory)
library(phangorn)
library(ggplot2)
library(ggdendro)
library(zoo)
library(dplyr)
library(dendextend)
```

Calculate the distance between trees:
```{r}
setwd("~/Desktop/analysis/")
trees<-read.tree("gnTrees_collection.tre")
clnum<-length(trees)

geod<-dist.multiPhylo(trees)
wrfd<-wRF.dist(trees)

wrfd<-as.matrix(wrfd)
tagname<-rownames(wrfd)
geod<-as.matrix(geod)
rownames(geod)<-tagname
colnames(geod)<-tagname
geod<-as.dist(geod)
```

Hierachical clustering + plotting dendrogram and heatmap:
```{r}
geod.hclust<-hclust(geod, method = "ward.D2")
```

```{r}
plot(geod.hclust, hang = -1, cex = 0.6)
```

```{r}
p <- ggplot(dend_data$segments) + 
  geom_segment(aes(x = x, y = y, xend = xend, yend = yend)) +
  geom_text(data = dend_data$labels, aes(x, y, label = label), hjust = -0.15, size = 2) + coord_flip() + scale_y_reverse(expand=c(0.09,0)) + 
  theme(axis.line.y = element_blank(), axis.ticks.y = element_blank(),axis.text.y = element_blank(), axis.title.y = element_blank(), axis.line.x = element_line(colour = "black"), axis.title.x=element_blank(), panel.background = element_rect(fill="white"),panel.grid = element_blank())
p
```

```{r}
gd.den<-as.dendrogram(geod.hclust)
dendr <- dendro_data(gd.den, type = "rectangle")

cut <- 4    # Number of clusters
clust <- cutree(geod.hclust, k = cut)               # find 'cut' clusters
clust.df <- data.frame(label = names(clust), cluster = clust)

# Split dendrogram into upper grey section and lower coloured section
height <- unique(dendr$segments$y)[order(unique(dendr$segments$y), decreasing = TRUE)]
cut.height <- mean(c(height[cut], height[cut-1]))
dendr$segments$line <- ifelse(dendr$segments$y == dendr$segments$yend &
   dendr$segments$y > cut.height, 1, 2)
dendr$segments$line <- ifelse(dendr$segments$yend  > cut.height, 1, dendr$segments$line)

# Number the clusters
dendr$segments$cluster <- c(-1, diff(dendr$segments$line))
change <- which(dendr$segments$cluster == 1)
for (i in 1:cut) dendr$segments$cluster[change[i]] = i + 1
dendr$segments$cluster <-  ifelse(dendr$segments$line == 1, 1, 
             ifelse(dendr$segments$cluster == 0, NA, dendr$segments$cluster))
dendr$segments$cluster <- na.locf(dendr$segments$cluster) 

# Consistent numbering between segment$cluster and label$cluster
clust.df$label <- factor(clust.df$label, levels = levels(dendr$labels$label))
clust.df <- arrange(clust.df, label)
clust.df$cluster <- factor((clust.df$cluster), levels = unique(clust.df$cluster), labels = (1:cut) + 1)
dendr[["labels"]] <- merge(dendr[["labels"]], clust.df, by = "label")

# Positions for cluster labels
n.rle <- rle(dendr$segments$cluster)
N <- cumsum(n.rle$lengths)
N <- N[seq(1, length(N), 2)] + 1
N.df <- dendr$segments[N, ]
N.df$cluster <- N.df$cluster - 1

# Plot the dendrogram
ggplot() + 
   geom_segment(data = segment(dendr), 
      aes(x=x, y=y, xend=xend, yend=yend, size=factor(line), colour=factor(cluster)), 
      lineend = "square", show.legend = FALSE) + 
   scale_colour_manual(values = c("grey60", rainbow(cut))) +
   scale_size_manual(values = c(.1, 1)) +
   geom_text(data = N.df, aes(x = x, y = y, label = factor(cluster),  colour = factor(cluster + 1)), 
      hjust = 1.5, size = 2, show.legend = FALSE) +
   geom_text(data = label(dendr), aes(x, y, label = label, colour = factor(cluster)), 
       hjust = -0.2, size = 3, show.legend = FALSE) +
   scale_y_reverse(expand = c(0.2, 0)) + 
   labs(x = NULL, y = NULL) +
   coord_flip() +
    theme(axis.line.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        panel.background = element_rect(fill = "white"),
        panel.grid = element_blank())
```

```{r}
gd.den <- as.dendrogram(geod.hclust) %>% set("labels_colors", value = c("tomato3","yellow3","forestgreen","deepskyblue3"), k = 4) %>% set("labels_cex", 0.4) %>% 
  set("branches_k_color", value = c("tomato3","yellow3","forestgreen","deepskyblue3"), k=4)
ggd1 <- as.ggdend(gd.den)
p <- ggplot(ggd1, horiz = TRUE, theme = theme_classic()) + theme(axis.line.y = element_blank(), axis.ticks.y = element_blank(),axis.text.y = element_blank(), axis.title.y = element_blank(), axis.line.x = element_line(colour = "black"), axis.title.x=element_blank(), panel.background = element_rect(fill="white"),panel.grid = element_blank()) 
p
```




