---
title: "Permutation Analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Extract log likelihood values from numerous files:
```{bash}
mkdir ~/Desktop/value
cd ~/Desktop/logLikelihood
for file in *
do
  name=$(echo "${file}")
  cat ${file} | cut -d $'\t' -f 2 > ~/Desktop/value/${name}
done

mv ~/Desktop/value/AutoWZgn_concatenation_logLhcollection ~/Desktop/
```

Generate a CSV-format file containing all the log likelihood values:
```{r}
setwd("~/Desktop/value")
out.file <- ""
file.names <- dir(pattern = "logLhcollection")
for(i in 1:length(file.names)){
  file<-read.table(file.names[i])
  out.file <- cbind(out.file, file)
}
write.csv(out.file, file = "logLkhcollection.csv")

da<-read.csv("~/Desktop/value/logLkhcollection.csv")
acdata<-read.table("~/Desktop/AutoWZgn_concatenation_logLhcollection", header = FALSE)
da<-cbind(acdata,da[,3:102])
pernum<-seq(1:100)
names(da)<-c("Actual.data", pernum)

pername<-c(" "," "," "," "," "," "," "," "," "," "," "," "," "," "," ")
kindex<-seq(1:15)
out.file<-cbind(kindex,da$Actual.data,pername,da[,2:101])
names(out.file)<-c("k","Actual data","Permutation data",pernum)
write.csv(out.file, file = "logLkhcollection.csv", row.names = FALSE)
```

Generate log likelihood table for plotting the graph:
```{r}
for(k in 1:14){
  da[k,]<-da[k,]-da[k+1,]
}
da<-rbind(da[1:14,])
dkindex<-seq(1:14)
peravrg<-apply(cbind(da[,2:101]), 1, mean)
persd<-apply(cbind(da[,2:101]), 1, sd)
daforR<-cbind(dkindex,da$Actual.data,peravrg,persd,da[,2:101])
names(daforR)<-c("dk","Actual data","Average","SD",pernum)
write.csv(daforR,file = "logLkhforR.csv", row.names = FALSE)
```
File sorting:
```{bash}
mv ~/Desktop/AutoWZgn_concatenation_logLhcollection ~/Desktop/value/
mv ~/Desktop/value ~/Desktop/logLikelihood
mv ~/Desktop/logLikelihood/value/logLkhcollection.csv ~/Desktop/
```

Loading package; Reading in data.
```{r echo=TRUE}
setwd("~/Desktop")
library(ggplot2)
library(tidyr)
logdata<-read.csv("logLkhforR.csv")
a<-logdata[,2:3]
write.csv(a,file = "a.csv")
a<-read.csv("a.csv")
a$X=c("k01","k02","k03","k04","k05","k06","k07","k08","k09","k10","k11","k12","k13","k14")
a<-as.data.frame(a)
names(a)<-c("cluster_num","Actual.data","Average")

logdata<-t(logdata)
b<-logdata[5:104,]
write.csv(b, file = "b.csv")
b<-read.csv("b.csv")
names(b)<-c("X","k01","k02","k03","k04","k05","k06","k07","k08","k09","k10","k11","k12","k13","k14")
num<-seq(1:100)
b$X=num
bb<-b[,2:14]
write.csv(bb, file = "b.csv")

a<-gather(a,group,dk,Actual.data:Average)
b<-gather(b,cluster_num,dk,k01:k14)
write.csv(a,file = "amd.csv")
write.csv(b,file = "bmd.csv")

a<-read.csv("amd.csv")
a<-as.data.frame(a)
b<-read.csv("bmd.csv")
b<-as.data.frame(b)
```

Plotting
```{r}
bp<-ggplot(b,aes(cluster_num,dk)) + geom_boxplot(data=b,aes(cluster_num,dk), color="grey")
res<- bp + geom_point(data=a[1:14,], aes(cluster_num,dk, color="Actual data")) + geom_line(data=a[1:14,], aes(cluster_num,dk, color="Actual data"), group=1) + geom_point(data=a[15:28,], aes(cluster_num,dk, color="Permutation data Mean")) + geom_line(data=a[15:28,], aes(cluster_num,dk, color="Permutation data Mean"), group=1)
res
```

```{bash include=FALSE}
if [ ! -d "~/Desktop/plot_graphs" ]; then mkdir plot_graphs; fi
rm -rf ~/Desktop/a.csv ~/Desktop/amd.csv ~/Desktop/b.csv ~/Desktop/bmd.csv
mv ~/Desktop/logLkhforR.csv ~/Desktop/plot_graphs
```

