---
title: "ultimate"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Multiple plot function
#
# ggplot objects can be passed in ..., or to plotlist (as a list of ggplot objects)
# - cols:   Number of columns in layout
# - layout: A matrix specifying the layout. If present, 'cols' is ignored.
#
# If the layout is something like matrix(c(1,2,3,3), nrow=2, byrow=TRUE),
# then plot 1 will go in the upper left, 2 will go in the upper right, and
# 3 will go all the way across the bottom.
#
multiplot <- function(..., plotlist=NULL, file, cols=1, layout=NULL) {
  library(grid)
  
  # Make a list from the ... arguments and plotlist
  plots <- c(list(...), plotlist)
  
  numPlots = length(plots)
  
  # If layout is NULL, then use 'cols' to determine layout
  if (is.null(layout)) {
    # Make the panel
    # ncol: Number of columns of plots
    # nrow: Number of rows needed, calculated from # of cols
    layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                     ncol = cols, nrow = ceiling(numPlots/cols))
  }
  
  if (numPlots==1) {
    print(plots[[1]])
    
  } else {
    # Set up the page
    grid.newpage()
    pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))
    
    # Make each plot, in the correct location
    for (i in 1:numPlots) {
      # Get the i,j matrix positions of the regions that contain this subplot
      matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))
      
      print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                      layout.pos.col = matchidx$col))
    }
  }
}
```

```{r}
library(distory)
library(phangorn)
library(ggplot2)
library(dendextend)
library(grid)
```

Calculate the distance between trees:
```{r}
setwd("~/Desktop/analysis/")
trees<-read.tree("gnTrees_collection.tre")
clnum<-length(trees)

geod<-dist.multiPhylo(trees)
wrfd<-wRF.dist(trees)

wrfd<-as.matrix(wrfd)
tagname<-rownames(wrfd)
geod<-as.matrix(geod)
rownames(geod)<-tagname
colnames(geod)<-tagname
geod<-as.dist(geod)
```

Hierachical clustering + plotting dendrogram and heatmap:
```{r}
geod.hclust<-hclust(geod, method = "ward.D2")
```

Polish dendrogram:
```{r}
gd.den <- as.dendrogram(geod.hclust) %>% set("labels_colors", value = "black") %>% set("labels_cex", 0.4) %>% 
  set("branches_k_color", value = c("coral2","deepskyblue2","magenta2", "aquamarine4"), k=4)
ggd1 <- as.ggdend(gd.den)

p <- ggplot(ggd1, horiz= TRUE, theme = NULL) + ylab("Height") + theme(axis.line.y = element_blank(), axis.ticks.y = element_blank(), axis.title.y = element_blank(), axis.text.y  = element_blank(), axis.line.x = element_blank(), panel.grid.major.x = element_line(colour = "gray90"), panel.grid.minor.x = element_blank(), panel.background = element_rect(fill = "white"), plot.margin = unit(c(1.3,0,0.3,0),"cm"), panel.grid.major.y = element_blank(), panel.grid.minor.y = element_blank())
```

Load cluster information data:
```{r}
dd<-read.table("~/Desktop/analysis/Cluster_Assignment_shortdata.summary")
names(dd)<-c("order","gene","Cluster1","Cluster2","Cluster3","Cluster4")
dd[,3:6] <- dd[,3:6] / 10
dd$order<-factor(dd$order)
A <- dd[1:57,]
B <- dd[58:75,]
```

```{r}
cl1A <- ggplot() + geom_bar(data = A, aes(x = order, y = Cluster1), stat = "identity", fill = "coral2", width = 0.9) + theme(axis.title.x = element_text(vjust = 2.5, hjust = 0.5),  axis.text.x = element_text(size = 7, vjust = 0.5, hjust = 1, angle = 90), axis.title.y = element_blank(), plot.margin = unit(c(0,0.1,0,0.6),"cm"), panel.grid.minor.y = element_blank(), panel.background = element_rect(color = "black")) + scale_y_continuous(limits = c(0,100)) + scale_x_discrete(position = "bottom", labels = A$gene) + labs(x="genes of high-supported(BS>=70%) trees")

cl1B <- ggplot() + geom_bar(data = B, aes(x = order, y = Cluster1), stat = "identity", fill = "coral2", width = 0.9) + theme(axis.title.x = element_text(vjust = 0, hjust = 0),  axis.text.x = element_text(size = 7, vjust = 0.5, hjust = 1, angle = 90), axis.title.y = element_blank(), plot.margin = unit(c(0,0.6,0.32,0.1),"cm"), panel.grid.minor.y = element_blank(), panel.background = element_rect(color = "black")) + scale_y_continuous(position = "right", limits = c(0,100)) + scale_x_discrete(position = "bottom", labels = B$gene) + labs(x="genes of low-supported(BS<70%) trees")



cl2A <- ggplot() + geom_bar(data = A, aes(x = order, y = Cluster2), stat = "identity", fill = "aquamarine4", width = 0.9) + theme(axis.title.x = element_blank(), axis.text.x.top = element_text(size = 7, vjust = 0.5, hjust = 0, angle = 90),axis.title.y = element_blank(), plot.margin = unit(c(0.5,0.1,0.1,0.6),"cm"), panel.grid.minor.y = element_blank(), panel.background = element_rect(color = "black")) + scale_x_discrete(position = "top", labels = A$gene) + scale_y_continuous(limits = c(0,100))

cl2B <- ggplot() + geom_bar(data = B, aes(x = order, y = Cluster2), stat = "identity", fill = "aquamarine4", width = 0.9) + theme(axis.title.x = element_blank(), axis.text.x.top = element_text(size = 7, vjust = 0.5, hjust = 0, angle = 90),axis.title.y = element_blank(), plot.margin = unit(c(0.8,0.6,0.1,0.1),"cm"), panel.grid.minor.y = element_blank(), panel.background = element_rect(color = "black")) + scale_x_discrete(position = "top", labels = B$gene) + scale_y_continuous(position = "right",  limits = c(0,100))



cl3A <- ggplot() + geom_bar(data = A, aes(x = order, y = Cluster3), stat = "identity", fill = "deepskyblue2", width = 0.9) + theme(axis.title.x = element_blank(), axis.text.x = element_blank(), axis.ticks.x = element_blank(), axis.title.y = element_text(vjust = -1.5, hjust = 2), plot.margin = unit(c(0,0.1,0,0),"cm"), panel.grid.minor.y = element_blank(), panel.background = element_rect(color = "black")) + scale_y_continuous(limits = c(0,100)) + labs(y="percentage(%)")

cl3B <- ggplot() + geom_bar(data = B, aes(x = order, y = Cluster3), stat = "identity", fill = "deepskyblue2", width = 0.9) + theme(axis.title.x = element_blank(), axis.text.x = element_blank(), axis.ticks.x = element_blank(), axis.title.y = element_text(vjust = -1.5, hjust = -1), plot.margin = unit(c(0,0.2,0,0.1),"cm"), panel.grid.minor.y = element_blank(), panel.background = element_rect(color = "black")) + scale_y_continuous(position = "right", limits = c(0,100)) + labs(y="percentage(%)")



cl4A <- ggplot() + geom_bar(data = A, aes(x = order, y = Cluster4), stat = "identity", fill = "magenta2", width = 0.9) + theme(axis.title.x = element_blank(), axis.text.x = element_blank(), axis.ticks.x = element_blank(), axis.title.y = element_blank(), plot.margin = unit(c(0,0.1,0,0.6),"cm"), panel.grid.minor.y = element_blank(), panel.background = element_rect(color = "black")) + scale_y_continuous(limits = c(0,100))

cl4B <- ggplot() + geom_bar(data = B, aes(x = order, y = Cluster4), stat = "identity", fill = "magenta2", width = 0.9) + theme(axis.title.x = element_blank(), axis.text.x = element_blank(), axis.ticks.x = element_blank(), axis.title.y = element_blank(), plot.margin = unit(c(0,0.6,0,0.1),"cm"), panel.grid.minor.y = element_blank(), panel.background = element_rect(color = "black")) + scale_y_continuous(position = "right",  limits = c(0,100))


#cl5 <- ggplot() + geom_bar(data = dd, aes(x = order, y = Cluster5), stat = "identity", fill = "magenta2", width = 0.9) + theme(axis.title.x = element_blank(), axis.text.x = element_text(size = 7, vjust = 0.5, hjust = 1, angle = 90), axis.title.y = element_blank(), plot.margin = unit(c(0,0,0,0),"cm"), panel.grid.minor.y = element_blank(), panel.background = element_rect(color = "black")) + scale_x_discrete(position = "bottom", labels = dd$gene) + scale_y_continuous(sec.axis = dup_axis(),  limits = c(0,100))
```

```{R}
layout <- matrix(c(1,2,2,2,3,1,2,2,2,3,1,2,2,2,3,1,4,4,4,5,1,4,4,4,5,1,6,6,6,7,1,6,6,6,7,1,8,8,8,9,1,8,8,8,9,1,8,8,8,9),10,5,byrow = TRUE)
svg("ClusterAssign.svg", width = 15, height = 8)
multiplot(p,cl2A,cl2B,cl4A,cl4B,cl3A,cl3B,cl1A,cl1B,layout = layout)
dev.off()
```

